### ISSUE TITLE
Recebendo notificação de atualização?

### ISSUE THREAD

**Issue by ccrvlh** [mvrozanti/rastreamento-correios#1]
Olá.
Obrigado pela lib.
É possível receber notificação de atualização de status?
O Correios já oferece isso através de mensagem de texto, mas não achei uma rota no webservice deles.
Abs

**Comment by mvrozanti** [comment]
Olá. Que bom que esse projeto está sendo útil.

Essa capacidade que vc mencionou é possível através de um script que execute `rastrear.sh` periodicamente.

Algo do tipo, em bash:
```
while true; do
  ./rastrear.sh seu_codigo_de_rastreamento | grep "entregue" && beep 
  sleep periodo_em_segundos
done
```

É claro que esse script depende de identificar quais status vc quer que gerem notificação, mas deve ser muito simples. O ideal seria os correios permitirem usar algum método de subscription ou mesmo uma API. Mas como não temos isso, esse script seria a coisa mais próxima a realizar o que vc quer.

Como este issue não é exatamente uma melhoria, vou fechá-lo, mas sinta-se à vontade para continuar a conversa por aqui.
